# assistant/keywords.py
# Raw phrases you provided. Keep as-is; we normalize at runtime.
RAW_ENGINEERING_TERMS = [
    "Computer Science & Engineering", "Programming Basics", "Programming Languages",
    "C/C++", "Basic Syntax", "Control Structures", "Functions", "Arrays & Pointers",
    "Classes & Objects", "Memory Management", "Python", "Data Types", "Control Flow",
    "Libraries & Packages", "Object-Oriented Programming", "Java", "Exception Handling",
    "Collections Framework", "Multithreading", "JavaScript", "DOM Manipulation", "Events",
    "Async Programming", "ES6+ Features", "Frameworks (React, Angular, Vue)",
    "Basic Tools & Environment", "Development Environment", "IDEs (VS Code, Eclipse, PyCharm)",
    "Code Editors", "Compilers & Interpreters", "Debuggers", "Version Control (Git)",
    "Package Managers", "Web Technologies Basics", "HTML5", "CSS3", "JavaScript Basics",
    "HTTP Protocol", "Web Servers", "API Basics", "Theoretical Concepts", "Computation Theory",
    "Automata Theory & Formal Languages", "Turing Machines & Computability",
    "Computational Complexity", "P vs NP Problem", "Algorithm Analysis", "Graph Theory",
    "Quantum Computing Theory", "Database Theory", "Relational Algebra", "Normalization Theory",
    "Transaction Processing", "Concurrency Control", "Database Recovery", "Query Optimization",
    "Programming Paradigms", "Object-Oriented Theory", "Functional Programming",
    "Logic Programming", "Concurrent Programming", "Distributed Systems Theory", "Type Theory",
    "Core Subjects", "Programming & Data Structures", "Algorithm Design",
    "Data Structure Implementation", "Time & Space Complexity", "File Structures",
    "Index Structures", "Operating Systems", "Process Management", "File Systems",
    "I/O Systems", "Deadlock Handling", "Security & Protection", "Computer Networks",
    "Network Architecture", "Protocol Layers", "Routing Algorithms", "Quality of Service",
    "Wireless Networks", "Trending Technologies", "Artificial Intelligence", "Machine Learning",
    "Deep Learning", "Natural Language Processing", "Computer Vision", "Robotics", "Expert Systems",
    "Cloud Computing", "Virtualization", "Container Technology", "Microservices",
    "Serverless Computing", "Cloud Security", "Edge Computing", "Blockchain", "Cryptography",
    "Smart Contracts", "Distributed Ledger", "Consensus Algorithms", "Cryptocurrency",
    "Blockchain Security", "Important Skills", "Software Development", "Testing Methodologies",
    "DevOps Practices", "Agile Methods", "Code Optimization", "Documentation", "System Design",
    "Architecture Patterns", "Design Patterns", "Scalability", "Performance Optimization",
    "Security Design", "API Design", "Mechanical Engineering", "Basic Tools & Concepts",
    "Engineering Drawing", "Geometric Constructions", "Orthographic Projections",
    "Isometric Views", "Sectional Views", "Dimensioning", "Tolerancing", "Basic Workshop Practice",
    "Measuring Tools", "Vernier Caliper", "Micrometer", "Height Gauge", "Dial Indicators",
    "Hand Tools", "Files", "Hammers", "Chisels", "Screwdrivers", "Machine Tools", "Lathe",
    "Drilling", "Milling", "Grinding", "Basic Materials", "Metals", "Ferrous Metals",
    "Non-ferrous Metals", "Non-metals", "Polymers", "Ceramics", "Composites", "Core Subjects",
    "Mechanics", "Classical Mechanics", "Quantum Mechanics", "Fluid Mechanics",
    "Solid Mechanics", "Kinematics", "Dynamics", "Thermodynamics", "Laws of Thermodynamics",
    "Heat Transfer", "Mass Transfer", "Phase Transitions", "Combustion Theory",
    "Statistical Mechanics", "Materials Science", "Crystal Structure", "Material Properties",
    "Phase Diagrams", "Failure Theories", "Composite Materials", "Nanomaterials",
    "Electrical Engineering", "Circuit Basics", "Voltage, Current, Resistance", "Ohm's Law",
    "Kirchhoff's Laws", "Series & Parallel Circuits", "AC/DC Basics", "Power & Energy",
    "Basic Components", "Resistors", "Types", "Color Coding", "Power Rating", "Capacitors",
    "Charging/Discharging", "Applications", "Inductors", "Properties", "Diodes", "PN Junction",
    "Transistors", "BJT", "FET", "Basic Operations", "Measuring Instruments",
    "Multimeter", "Oscilloscope", "Function Generator", "Power Supply", "LCR Meter",
    "Civil Engineering", "Surveying Basics", "Chain Surveying", "Compass Surveying", "Leveling",
    "Theodolite", "Total Station", "GPS Basics", "Construction Materials", "Cement",
    "Types", "Tests", "Aggregates", "Classification", "Properties", "Concrete", "Mix Design",
    "Testing", "Steel", "Applications", "Structural Concepts", "Stress & Strain",
    "Beams & Columns", "Foundations", "Load Types", "Basic Analysis", "Electronics & Communication",
    "Active Components", "ICs", "LEDs", "Passive Components", "Transformers", "Communication Basics",
    "Signals & Systems", "Modulation Types", "Antennas", "Protocols", "Chemical Engineering",
    "Chemistry Fundamentals", "Organic Chemistry", "Inorganic Chemistry", "Physical Chemistry",
    "Analytical Methods", "Lab Techniques", "Safety Protocols", "Basic Unit Operations",
    "Fluid Flow", "Separation Processes", "Mixing", "Size Reduction", "Process Equipment",
    "Pumps", "Heat Exchangers", "Distillation Columns", "Reactors", "Dryers", "Aerospace Engineering",
    "Aircraft Components", "Airframe", "Propulsion", "Landing Gear", "Control Surfaces",
    "Navigation Systems", "Safety Systems", "Aerodynamics Basics", "Airfoil Theory",
    "Lift & Drag", "Flight Controls", "Stability", "Aircraft Performance", "Biomedical Engineering",
    "Medical Electronics", "Sensors", "Filters", "Signal Processing", "Safety Standards",
    "Biomaterials Basics", "Testing Methods", "Compatibility", "Common Engineering Skills",
    "Basic Computer Skills", "Office Tools", "Word Processing", "Spreadsheets", "Presentations",
    "Project Management", "Technical Software", "CAD Basics", "Simulation Tools",
    "Workshop Safety", "Personal Protection", "Equipment Safety", "Emergency Procedures", "Algorithms",
]

# Optionally ignore ultra-generic phrases that cause false positives:
_EXCLUDE_EXACT = {
    "types", "tests", "applications", "properties",
    "core subjects", "important skills", "basic tools & concepts",
}

# Final normalized list used by the matcher
ENGINEERING_TERMS = [
    " ".join(term.lower().split())
    for term in RAW_ENGINEERING_TERMS
    if term and term.strip() and term.lower() not in _EXCLUDE_EXACT
]
